### PR TITLE
Added Reuben Brenner-Adams's project proposal

### PR DESCRIPTION
**Pull request by kangareuben**

### CODE REVIEW

**Comment by msoucy** [comment]
Please see #2

**Comment by kangareuben** [comment]
Revised file structure; please re-evaluate and merge if correct.

**Comment by msoucy** [comment]
If you rename it to README.md it'll show up when you browse the directory on Github

**Comment by kangareuben** [comment]
Understood and changed. Sorry it's taken me a few tries.

**Comment by liam-middlebrook** [comment]
Lgtm :+1:

**Pull request merged**
