### PR TITLE
Rename directory and update partnership in readme

### PR DESCRIPTION
**Pull request by kocsenc**

### CODE REVIEW

**Comment by kocsenc** [comment]
@KevinMGranger Plz review, let me know of any changes.

**Comment by KevinMGranger** [comment]
:shipit:

**Comment by liam-middlebrook** [comment]
@kocsenc @KevinMGranger please don't use spaces in your directory names :-1:

**Comment by KevinMGranger** [comment]
@liam-middlebrook didn't notice that part. The GitHub UI doesn't highlight renames well!

Also, get a shell that sucks less kthx

**Comment by kocsenc** [comment]
@liam-middlebrook i'll update

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Pull request merged**
